// user types
export const LOGIN = "LOGIN";
export const GET_USER = "GET_USER";
export const LOGOUT = "LOGOUT";

// QA types
// export const POST_QUESTION = "POST_QUESTION"
export const GET_DASHBOARD_QUESTIONS = "GET_DASHBOARD_QUESTIONS";
export const GET_HOME_QUESTIONS = "GET_HOME_QUESTIONS";
export const GET_MORE_HOME_QUESTIONS = "GET_MORE_HOME_QUESTIONS";
export const GET_MORE_DASHBOARD_QUESTIONS = "GET_MORE_DASHBOARD_QUESTIONS";
